### ISSUE TITLE
Support generic detector

### ISSUE THREAD

**Issue by christophwelling** [nu-radio/NuRadioMC#119]
Currently NuRadioMC can only use the normal detector. It would be nice if the GenericDetector class I implemented in NuRadioReco could also be used.

**Comment by anelles** [comment]
Is adressed in #118

**Comment by anelles** [comment]
@christophwelling was my statement actually correct that NuRadioMC can do this now, or was I too fast and this is still open?

**Comment by christophwelling** [comment]
Depends on what you mean. This issue was about NuRadioMC being able to use the GenericDetector class as well as the standard Detector class. That is done.
If you mean that fancy 3D plot for the event display, I still have to add that. The event display makeover is on my to-do list, though.
