### ISSUE TITLE
Take utilities from NuRadioReco

### ISSUE THREAD

**Issue by christophwelling** [nu-radio/NuRadioMC#152]
There are some utilities (e.g. fft and units) that are just copies of a utility in NuRadioReco. Since NuRadioMC has NuRadioReco as a dependency anyway, I suggest we remove these duplicates and use the ones from NuRadioReco. Otherwise, this is just additional maintenance and can lead to errors.

**Comment by anelles** [comment]
All for it!

**Comment by cg-laser** [comment]
sounds good to me as well

**Comment by anelles** [comment]
Addressed in #153
