### ISSUE TITLE
sim channels are not downsampled to detector resolution

### ISSUE THREAD

**Issue by cg-laser** [nu-radio/NuRadioMC#263]
sim channels are not automatically downsampled to detector resolution before they are written to the nur file. Instead they still have the sampling rate that was internally used during the simulations. This blows up the data volume.

**Comment by anelles** [comment]
@cg-laser, this looks like it has been fixed. Or was the reference a mistake?

**Comment by cg-laser** [comment]
yes it is fixed, forgot to close it
