### ISSUE TITLE
move definition of attenuation length into separate utility class

### ISSUE THREAD

**Issue by cg-laser** [nu-radio/NuRadioMC#27]
Currently, the attenuation length model is part of the ray tracing code. We should move it into a separate utility class or even integrate it into the medium class.

A complication is that we also need to make the attenuation length available to the C++ implementation of the ray tracer. The clean solution would be to implement the attenuation length parameterization in C++ and provide a python wrapper. As this is just a static model, we could also just replicate the class in C (as we did for the units definition).

**Comment by anelles** [comment]
Has been implemented in NuRadioMC/utilities
