### ISSUE TITLE
Define solution type coding globally

### ISSUE THREAD

**Issue by christophwelling** [nu-radio/NuRadioMC#281]
Currently the mapping between solution type integers and strings
1=direct
2=refracted
3=reflected
is currently defined separately in several places in the code. It would be better to have this all in one place to make sure it is consistend everywhere.

**Comment by sjoerd-bouma** [comment]
I believe this was fixed by PR #297 - the solution types are available as a `dict` in `NuRadioMC.SignalProp.propagation`.
