### ISSUE TITLE
simulate tau decay channel (in event generator)

### ISSUE THREAD

**Issue by cg-laser** [nu-radio/NuRadioMC#29]
The branching ratios of a tau decay are 
~18% e- + 2nu's -> EM shower
~17% muon + 2nu's -> no shower (but maybe muon dE/dX energy loss?)
~64% hadronic decay -> starts hadronic shower, but a different shower than a nu NC interaction that starts right away with hundreds of partons)

The decay channel should be simulated in the event generator. 

For EM decays: Is all energy deposited into the electron? Or is also a significant fraction of the energy carried by the neutrinos?

**Comment by anelles** [comment]
We have a working tau decay now. Thanks to an earlier merge from @daniel-zid in #32 . Please remember to tag the issues that you are trying to fix in the merge commit.
