### ISSUE TITLE
Wiki page "How to contribute" incomplete

### ISSUE THREAD

**Issue by anelles** [nu-radio/NuRadioMC#328]
We could probably save ourselves some questions, if we updated: 

https://github.com/nu-radio/NuRadioMC/wiki/How-to-contribute

There is nothing implemented for a feature workflow and nothing for UNIX using git-flow (needed?)

**Comment by sjoerd-bouma** [comment]
This is hopefully addressed sufficiently by #368; if not, feel free to reopen this issue : )

The contributing guidelines can be found [here](https://nu-radio.github.io/NuRadioMC/Introduction/pages/contributing.html).
