### ISSUE TITLE
Install dependencies in run_tests.yaml overwrites (?) code actually in commit

### ISSUE THREAD

**Issue by sjoerd-bouma** [nu-radio/NuRadioMC#351]
The automatic tests in the github workflow run_tests.yaml overwrite code in the NuRadioReco module with code from a zip archive:
```
wget https://github.com/nu-radio/NuRadioReco/archive/refactor-pa.zip -O /tmp/NuRadioReco.zip
unzip /tmp/NuRadioReco.zip
mv NuRadioReco-refactor-pa/NuRadioReco $PWD/NuRadioReco
```

This means that instead of testing the code in the pushed commit, it will actually run the tests on code in this archive (which will trivially complete).

I ran into this when testing the documentation. If there is some very good reason to test this archive, I suggest we make a separate test for it. Otherwise, this should just be removed from `run_tests.yaml` ASAP.

**Comment by sjoerd-bouma** [comment]
@cg-laser Looks like github blames you for this... Please let me know if there's some reason to keep this, otherwise I will make a PR to remove it.

**Comment by anelles** [comment]
This looks like it was a temporary test, when we were moving from the old repo to the new repo, respectively when we wanted to test something with a something not in the master. Please make a PR to fix this, yes!

**Comment by cg-laser** [comment]
thanks for catching this and providing a fix!
