### ISSUE TITLE
Potential issue in Hilbert envelope?

### ISSUE THREAD

**Issue by shallmann** [nu-radio/NuRadioMC#352]
I was trying to use the get_hilbert_envelope function in the `BaseTrace` class, and didn't return what I expected (i expected `np.array(np.abs(h))`. Instead, only the first three items are returned (probably assumed that one has a 3D trace?), is that intended? Why do we want that?

https://github.com/nu-radio/NuRadioMC/blob/572d4f6382db4928b75581dda117c3f9e90b013d/NuRadioReco/framework/base_trace.py#L129

**Comment by anelles** [comment]
This looks like it was made to return the hilbert envelope for three components of the electric field. So the main axis seems to be wrong for the type of array that you are using this for. This shouldn't happen.

**Comment by anelles** [comment]
@cg-laser actually noticed this already in #304 , so this needs fixing.

**Comment by shallmann** [comment]
Fixed
