### ISSUE TITLE
Flavor in proposal showers

### ISSUE THREAD

**Issue by shallmann** [nu-radio/NuRadioMC#371]
In the list of PROPOSAL showers, the flavor is currently set as the `product.code` (ie. the shower code).

I copy over here the suggestion of Dave S, who noticed this:
Flavor:  85 = photonuclear, 83 = pair, 81 = brem
Interaction type: had/em
Energy is always the neutrino energy

Instead let me suggest

energy -> energy of particle at point of de/dx interaction
flavor -> identity of particle at point of interaction
interaction type -> 85 = photonuclear, 83 = pair, 81 = brem 

It should be possible to obtain the more appropriate 13/15 (i.e. mu tau) by replacing
```
                                  # Flavors are particle codes taken from NuRadioProposal.py
                                  data_sets_fiducial['flavors'][-1] = product.code
```

by taking the `code` of the `parent` rather than the `product`

**Comment by fschlueter** [comment]
Lol this is exactly what we did a year later with #486.

I will close this issue. Feel free to reopen if I missed the objective of it
