### ISSUE TITLE
Passing objects as keyword parameter to modules causes error in eventWriter

### ISSUE THREAD

**Issue by christophwelling** [nu-radio/NuRadioMC#427]
When certain objects (such as a detector instance) is passed to a module as a keyword parameter will cause an error with the eventWriter.
For example, changing
```
channelLengthAdjuster.run(event, station, detector)
eventWriter.run(event, station, det)
```
to
```
channelLengthAdjuster.run(event, station, det=detector)
eventWriter.run(event, station, det)
```
will cause the error 
```
File "/home/welling/Software/NuRadioMC/NuRadioReco/framework/event.py", line 421, in serialize
    return pickle.dumps(data, protocol=4)
AttributeError: Can't pickle local object 'Query._generate_test.<locals>.<lambda>'
```
This can happen with almost any module, not just the channelLengthAdjuster.
The problem is that the keyword parameters with which the run() method is called are stored in the event object.  So when the detector is passed as a keyword parameter, it is in this list. Then the eventWriter does not know what to do with it and throws an error.

I don't really know a good way to fix this, but I think we really should. This is an easy problem to run into, and difficult to figure out if you don't know how NuRadioReco works under the hood.

Thanks to Ryan Rice-Smith for finding this bug.

**Comment by sjoerd-bouma** [comment]
Closing as fixed by #572
