### ISSUE TITLE
NuRadioProposal .pop() in ordered indices looks wrong?

### ISSUE THREAD

**Issue by shallmann** [nu-radio/NuRadioMC#461]
https://github.com/nu-radio/NuRadioMC/blob/871a625519eb43f21bbfb527271008edb621ece2/NuRadioMC/EvtGen/NuRadioProposal.py#L622

Maybe not an issue, because there are not multiple decay muons to be propagated per particle? Otherwise popping indices [1,2] as in the loop defined e.g in [0,1,2,3,4] would pop [1,3] rather than [1,2] ...

**Comment by Jean1995** [comment]
Good catch. So it should probably look something like

`decay_products = np.delete(decay_products, repropagated_muon_indices).tolist()`

(There is probably a nicer way to write this line, I just have to think a bit more about it 😅 )

**Comment by shallmann** [comment]
or reverse ordering indices before popping would also be sufficient ;)

**Comment by shallmann** [comment]
accounted for in PR #458

**Comment by fschlueter** [comment]
can that be closed?

**Comment by shallmann** [comment]
This has been fixed
