### ISSUE TITLE
Feldman Cousins list contains wrong number

### ISSUE THREAD

**Issue by shallmann** [nu-radio/NuRadioMC#512]
![Uploading Screenshot 2023-03-15 at 10.55.07.png…]()

**Comment by fschlueter** [comment]
No picture uploaded yet :D

**Comment by lpyras** [comment]
<img width="477" alt="Screenshot 2023-03-15 at 10 55 07" src="https://user-images.githubusercontent.com/56539848/225278637-71c33aae-3fcc-4342-bbf7-357b8fa81b57.png">
Here is the file
