### ISSUE TITLE
Cleanup voltageToEfieldConverter

### ISSUE THREAD

**Issue by cg-laser** [nu-radio/NuRadioMC#527]
The voltageToEfieldConverter needs some cleanup. 
The solution to the electric field for two antennas is calculated twice and never used: https://github.com/nu-radio/NuRadioMC/blob/develop/NuRadioReco/modules/voltageToEfieldConverter.py#L161-L171

Intended behavior: In case of just 2 antennas, don't use the chi2 minimization but instead us the exact solution to calculate the efield.

**Comment by MijnheerD** [comment]
@karenterveer had a look at this module last week, and I think this has now been fixed?

**Comment by sjoerd-bouma** [comment]
It was me, actually. The code could be tidied up by removing the lines @cg-laser mentions, but in the case of just 2 antennas, the chi2 solution is equivalent to the exact solution (which I verified), with the only benefit to using a separate exact calculation for that case (that I can see) a small improvement in performance.

This has not been implemented yet but I don't think it's a particularly high priority either.

**Comment by cg-laser** [comment]
great that you verified that! I agree, then we don't need to implement a special case. We could add a comment though

**Comment by sjoerd-bouma** [comment]
Closed by #758
