### ISSUE TITLE
Cannot write out event after using eventWriter with detector option

### ISSUE THREAD

**Issue by MijnheerD** [nu-radio/NuRadioMC#568]
**Describe the issue**
When saving an `Event` with a detector description, the same `Event` cannot be saved again (to a different file for example). Attempting to do this will throw a `TypeError: cannot pickle '_io.TextIOWrapper' object` error.

This is due to how the `Event` object saves the modules applied to it. After running an `eventWriter` with both `Event` and `Detector` objects specified, the `Detector` object becomes a part of the `__modules_event` list of the `Event` which is serialized when writing out the `Event`. However, the `Detector` object cannot be pickled (I guess due to the TinyDB objects contained within it), so when attempting to `serialize` the `Event` again, it throws the error mentioned above.

**Expected behavior**
I should be able to save an `Event` twice in the same script, for example to store it before and after calibration.

I don't know what the cleanest solution would be, but my suggestion would be to **not** add `eventWriter` operations to the `__modules_event` list, as it seems pretty obvious this module was applied if there exists a .nur file :-)

**Additional context**
MWE:
```python
from NuRadioReco.detector import detector
from NuRadioReco.framework import event
from NuRadioReco.modules.io import eventWriter

evt = event.Event(0, 0)
det = detector.Detector('NuRadioReco/examples/example_data/arianna_station_32.json')

eventWriter = eventWriter.eventWriter()
eventWriter.begin(f'NuRadioReco/examples/LOFAR_data/test.nur')
eventWriter.run(evt, det=det)
eventWriter.end()

eventWriter.begin(f'NuRadioReco/examples/LOFAR_data/test2.nur')
eventWriter.run(evt, det=det)  # this line will throw a TypeError, even if the "det=det" argument is removed
eventWriter.end()
```

**Comment by fschlueter** [comment]
Hi @MijnheerD and others, 

The `eventWriter` has as optional argument (as a `kwargs`) the detector. When an event is serialised, the `kwargs` pass to all modules running on this event are serialised as well. However, the detector class can not be simply serialised and we also do not want that. But I wondered, why did that just shows up when running the writer twice? Well in fact the first time we store the event, i.e., run the eventWriter, this module and its kwargs are not added to the list (`__modules_event`) to be serialised yet. I guess that is a bug in itself. 

So what to do:

- We can, as you suggest, not add certain modules from being added to the list `__modules_event`. But than this problem would show up again once we have a module which uses the detector as kwargs.
- We can specify which objects within the kwargs are getting serialised based on its class type, keyword in `event.py`

BTW, whether an argument is an `args` or a `kwargs` does not depend on the definition in the method but on how you pass the arguments right? That mean that we might miss important arguments which were passed without its keyword. We should fix that as well. Any opinions @shallmann 

PS: Excellent and very detailed issue description.
