### ISSUE TITLE
Time adjuster creates invalid waveforms

### ISSUE THREAD

**Issue by colemanalan** [nu-radio/NuRadioMC#582]
When the wavefom is assigned in `triggerTimeAdjuster`:
https://github.com/nu-radio/NuRadioMC/blob/7b5b259c2b06684b32f49c5610a6021e767cdadb/NuRadioReco/modules/triggerTimeAdjuster.py#L96

there is an explicit check when `set_trace` is performed to ensure that waveforms cannot have an odd length. However, this module can generate waveforms with an odd length when cutting when the pulse is too close to the "right-most" edge or more generally when a pre-trigger time is requested that is larger than the waveform. This causes the whole program to crash.

Example:
If this function is called, for a desired waveform length of 1024 bins at 2.4 GS/s but is currently sampled at 5 GS/s, then this module will try to make waveforms that are: 1024 * 5 / 2.4 = 2133 bins long
https://github.com/nu-radio/NuRadioMC/blob/7b5b259c2b06684b32f49c5610a6021e767cdadb/NuRadioReco/modules/triggerTimeAdjuster.py#L63

**Comment by sjoerd-bouma** [comment]
I've already fixed this on #526, but I should finally implement the trigger time storage as requested by Christian so that can be merged, apologies.

**Comment by sjoerd-bouma** [comment]
Closed by #526
