### ISSUE TITLE
Most examples in SignalGen class are broken

### ISSUE THREAD

**Issue by clark2668** [nu-radio/NuRadioMC#61]
Many of the tests in the SignalGen class rely on calls like: 

`import NuRadioMC.SignalGen.parametrizations as param`
`spec4 = param.get_frequency_spectrum(E, theta, ff, em, n_index, R, model='ZHS1992')`

But the `get_frequency_spectrum` method was removed, so these no longer work.

**Comment by anelles** [comment]
I suggest that we write new tests. @cg-laser probably the figures you made for the paper could replace these tests, no?

**Comment by anelles** [comment]
I would suggest to move these to the general tests and remove all broken ones. As in #106 we are overhauling the whole testing anyway.

**Comment by anelles** [comment]
We are testing the SignalGen examples now on the built-bot. Older examples may no longer work.
