### ISSUE TITLE
Store arguments with which a detector is initialised in  nur files.

### ISSUE THREAD

**Issue by fschlueter** [nu-radio/NuRadioMC#663]
Currently we are not storing arguments such as `antenna_by_depth` in the nur files. Hence, when reading a detector from a nur file the default values are used.

**Comment by MijnheerD** [comment]
This issue comes up when loading a normal Detector from a .nur file for an in-air experiment. Because the `antenna_by_depth` keyword defaults to `True`, the naming for the antenna pattern files is messed up when using the Detector which is read in.
